bradleyfalzon/gopherci

internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go
This assumes some parameters are correct for organisations as well
as user repos, I'm not convinced but GitHub docs aren't clear.
=> Remove hardcoded repo paths when posting pr comments

internal/queue/gcp-pubsub.go
Not before the context closes, mistake on my behalf.
=> GCPPubSubQueue should log closing after context closes

internal/analyser/analyser.go, internal/analyser/analyser_test.go, migrations/3_tools_dominikh.sql
This is a very special release where we're finally adding dominikh's gosimple, staticcheck and unused tools.
We're still far from having user configurable tools, but these are of high enough quality to be useful and low enough false positives that they shouldn't cause any problems being enabled globally.
We've had to make a minor change to gopherci to support a new option in revgrep, see the commit messages for more information.
Resolves #40.
=> Add dominikh's gosimple, staticcheck and unused tools

internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/analyser/docker.go, internal/analyser/docker_test.go, internal/analyser/filesystem.go, internal/analyser/filesystem_test.go, internal/github/handlers.go, internal/github/handlers_test.go
Currently we clone into `$GOPATH/src/gopherci` but any project that
imports sub packages in the same repository, would have those
dependencies go get'd (go got?).
If the project imported internal packages, those couldn't be built
at all with the error `use of internal package not allowed`.
This fix attempts to guess the import path, based on the URL by:
- Getting the base repo's HTML URL `https://github.com/owner/repo`
- Strippping the scheme `github.com/owner/repo`
- Docker or file system executer runs command with that as the
working directory
- All clones, tools etc, are then executed in the repositories
working directory, which should be `$GOPATH/src/github.com/owner/repo`
I'm not a big fan of this is done (just stripping the scheme), but
the only edge case I can forsee are those with …
=> Clone to import path in $GOPATH/src/

internal/queue/gcp-pubsub.go, internal/queue/gcp-pubsub_test.go, internal/queue/memory_test.go
There's been a couple cases now (#46) when creating the topic on
GCP Pub/Sub that has caused GopherCI to block and never start.
This change creates a context with a timeout for use by the
various pub sub sdk's setup methods with a fixed (hardcoded)
timeout. A test is also provided which sets a very low timeout and
ensures a context.DeadLineExceeded is received.
Unfortunately, a leaktest needed to be removed from an adjacent
test, which caused false positives. I did not have time to correctly
debug this situation.
Fixes #46.
=> Add timeout to GCPPubSub connection setup

internal/github/handlers.go, internal/github/handlers_test.go
Previously we were only checking a PR when it was first opened,
and not when additional commits were pushed.
There was no reason we were ignoring it, so this commit supports
that behaviour now.
We'll also build on reopened events, see #24 for some discussion
as there's room to optimise this workflow, but I get one main
benefit that it makes development faster by just having to close
and open a PR to have it rebuilt.
Resolves #24 and #25.
=> Support synchronize and reopened events on GitHub Pull Requests

internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/github/installation_test.go
But ensure the Statuses API includes a message which states how
many comments were suppressed.
In the future, the user will be able to see all the issues on a
dedicated page, see #28.
Fixes #58.
=> Suppress writing comments after exceeding maxIssueComments

internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/queue/gcp-pubsub.go, main.go
This is accomplished with a few refactors.
We no longer fetch the diff URL provided in a Pull Request event,
it was convenient, but it's not available in Pushes and we can
easily calculate it ourselves without the need for the extra
lookup. This was GitHub specific too, other providers may not have
provided that URL.
Analyse does need to process a Push differently than a Pull Request,
and this is managed by the EventType type.
We ignore the GitHub push event's Before SHA ref, during testing
force pushes, this would be the ref of the commit that's being
"overwritten" so it wouldn't exist when clonsed. Unlike a
non-forced push, where the commit exists after the clone. So instead
of using Before, we use After~len(Commits), so no matter how many
commits are being pushed, or whether the …
=> Support GitHub PushEvent

internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go
When viewing a GitHub pull request, either via API or through github.com,
the status API will show the status based on either the pull request or
the last commit if either have a status (eg success/failed).
If both have a status, and both use the same context "ci/gopherci",
the statuses would overwrite each other. For example, if the pull
request status API returned "success: Found 2 issues", but the user
pushed another commit, the push could set the status to "success:
Found 1 issue". This would overwrite the pull request's status which
tracks the entire pull request.
This change follows Travis CI's naming convention, although they may
be doing this for other requests, by adding a "/pr" or "/push" suffix,
such as "ci/gopherci/pr" and "ci/gopherci/push".
=> Add /pr or /push suffix to GitHub Status API context

.env.example, CONTRIBUTING.md, integration_test.go, testdata/init.sh, testdata/issue-comments.sh
This is the first attempt at running some basic integration tests.
Right now, the tests focus on PRs only and ensures a comment is left.
It includes a small help IntegrationTest to start GopherCI and some
helper functions, such as waiting for status to change from pending
to success.
Currently, these are not automatically executed in CI.
=> Add integration tests.

integration_test.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/github/installation_test.go, testdata/dupe-issue-comments.sh
Before writing comments on an issue, this change filters
those issues to only issues that have not been posted already.
Additionally, the WriteIssues function was refactored slightly
to only post comments, previously it was only writing a maximum
amount before returning the number of comments suppressed. This
max comments functionality has been added to the new FilterIssues
method.
The integration tests have also been expanded to include
a test, although, this wasn't strictly necessary. The integration
tests have also been updated to support the GitHub API's new
context arguments.
Resolves #62.
=> Don't post duplicate comments on a PR

integration_test.go, internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/analyser/docker.go, internal/analyser/docker_test.go, internal/analyser/filesystem.go, internal/github/handlers_test.go, testdata/issue-comments-ignore-generated.sh
We consider generated code, anything that appears to be generated
or is in a vendor/testdata directory. GopherCI uses
github.com/gopherci/isFileGenerated which mostly uses a function
provided by github.com/shurcooL/go.
In using isFileGenerated, it makes it difficult for a user to provide
additional files to be ignored, this would need to be implemented in
similar areas by other method if we decide to support that option.
This causes all issues from generated code to be ignored, there
will be no option to only comment, or only set the build to failed
as the issue will be ignored as soon as it's detected.
An additional integration test has been provided, because although
there are unit tests, it's possible the underlying tools misbehave
or change their implementation details.
Resolves #57.
=> Ignore issues in generated code, or vendored/testdata directories

internal/github/github.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/queue/gcp-pubsub.go, internal/queue/gcp-pubsub_test.go, internal/queue/memory.go, internal/queue/memory_test.go, internal/queue/queue.go, main.go
Google have recently made some breaking changes to their Pub/Sub
client API to support new high performance streaming methods.
https://groups.google.com/forum/#!topic/google-api-go-announce/aaqRDIQ3rvU/discussion
https://groups.google.com/forum/#!topic/google-api-go-announce/8pt6oetAdKc/discussion
The main change is the new methods don't easily support blocking
operations, nor one message at a time use cases. This is being
discussed: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/566
This change attempts to use the new API but in a blocking method
indirectly discussed: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/569
Since finishing and testing this method, which was successful, it
appears Google is discussing this use case further internally, so
this may …
=> GCPPubSub refactor to support new streaming client API

internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/db/db.go, internal/db/mockdb.go, internal/db/sqldb.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/github/installation_test.go, migrations/4_analysis.sql
This provides the foundations for a web view (discussed in #28),
so users can view the issues without relying on inline or issue
comments.
This also provides a mechanism to time how long the analysis is
taking as well as a per tool timing metric. This allows us to better
understand how much time different repositories or installations spend
checking.
We record which tools were executed, even if no issues were detected
so the user knows which checks passed. This will cause the analysis_tool
table to become very large over time.
Relates to #3.
=> Write analysis to the database

.env.example, internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/db/db.go, internal/db/db_test.go, internal/db/mockdb.go, internal/db/sqldb.go, internal/github/github.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/web/templates/analysis.tmpl, internal/web/templates/error.tmpl, internal/web/templates/footer.tmpl, internal/web/templates/header.tmpl, internal/web/web.go, main.go
GopherCI itself has the ability to show the results of an analysis.
This is the first version, very rough cut.
It's achieved by creating an internal package web, containing static
assets, templates and the handlers for the web views. This is done
to best compartmentalise the web components from the CI checks as
much as possible, as GopherCI is a CI tool, not a web view into the
results. I don't imagine too much more functionality being added
that isn't directly related to viewing analysis results.
Additional changes were required, there was a bug when writing results
to the database, it was using a TIME(3) field but trying to store
seconds in it, so results above 60 failed. The new Duration field
resolves this, and cleans up the marshalling of dates in and out of the
database. …
=> Working web UI

internal/db/db.go, internal/db/db_test.go, internal/db/sqldb.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/github/installation_test.go, internal/web/static/site.css, internal/web/templates/analysis.tmpl, internal/web/templates/footer.tmpl, internal/web/templates/header.tmpl, internal/web/vcsviewer.go, internal/web/vcsviewer_test.go, internal/web/web.go, main.go, migrations/5_analysis_extra_fields.sql
We'll do this by storing before and after commits and pr number in
the analysis table. They'll be used for display, but also to generate API
endpoints instead of storing the actual API URLs.
https://api.github.com/repositories/{repository_id}/pulls/{request_number}
https://api.github.com/repositories/{repository_id}/compare/{commit_from}...{commit_after}
GitLab has similar URLs which only requires merge request number or from
and to SHAs.
We've also created a new interface called VCSViewer, this will be used
to abstract away the VCS, such as GitHub, GitLab and others, providing
a uniform interface. It will likely be expanded upon in the furture to
return other information. github.Installation will now begin to implement
this interface.
The recently added package "web" currently cares for …
=> View a diff of the changes in the analysis view

integration_test.go, internal/analyser/analyser.go, internal/analyser/analyser_test.go, testdata/new-go-repository.sh
For a new repository, or a branch which doesn't have any history
(tracking a different git tree), we can't get a diff using the
"git diff abcd~5...abcd" method.
Instead, we'll try that way, and if it fails, try to get the diff
using "git show abcd".
I chose not to have the analyser check the ref "abcd~5" exists first
to help simplify the code, with less conditionals, but I'm not
convinced this is any more readable and potentially less reliable.
Therefore, it may be refactored in the future.
I've added an integration test for this as well, to ensure the
behaviour with git is always tested and not mocked like it is in the
unit test.
Fixes #79.
=> Handle repositories with no history (eg new)

internal/analyser/analyser.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/github/installation_test.go
This commit sets up a better framework for ignoring certain GitHub
events early, before they're sent to the queue.
We don't queue them because some organisations have many non-Go
repositories and queuing all those jobs to just be immediately
discarded was becoming a little wasteful. In the future, I'm happy
for this decision to be reversed.
This is implemented in a GitHub specific manner, as it ensured the
events would be discarded before a clone of the repository occurred.
Resolves #80.
Related to #73.
Related video: https://youtu.be/fjPJDC-0hXA
=> Ignore GitHub events early, such as no Go repos and no installation

integration_test.go, internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/analyser/configReader.go, internal/analyser/configReader_test.go, internal/github/handlers.go, internal/github/handlers_test.go, testdata/apt-cgo.sh
Broken into 3 commits:
```
Users should be able to apply per repository configuration for GopherCI via
a config file in the repository, this allows non-admin users to modify
GopherCI on a per repository basis if they have write access. Which practically
means users can also have their pull request modify GopherCI if they require
additional packages to be installed (for cgo for example) or if they want to
modify the tools being run.
We achieve this by including a YAMLConfig which implements a configReader
interface, an interface was chosen primarily to keep tests simpler, but
the analyser doesn't really care where the config came from, just that it's
able to receive one.
The YAMLConfig should be preloaded with the global settings and then it should
filter the config based on reading the …
```
=> Add .gopherci.yml support and use it to install APT packages for CGO.

internal/analyser/analyser_test.go, internal/db/db.go, internal/db/mockdb.go, internal/db/sqldb.go, internal/github/handlers.go, internal/web/templates/analysis.tmpl, internal/web/web.go
DB StartAnalysis should take commitFrom, commitTo, and requestNumber:
```
Previously these fields were only added after a successful analysis.
This change makes those three required fields a part of the constructor
so no matter what failure scenario there is, those fields are still set.
The other option is to ensure a failed analysis still sets some of
these fields, but there may be some scenarios where those fields may
have been missed, such as a panic.
```
Analysis page fetching diff should not be a critical error:
```
The db.Analysis type contains a list of the issues per tool that were
stored in the database. We use these in two ways:
A) Provide it to web.DiffIssues function to combine a diff/patch with
the issue to show the issue inline.
B) Show a summary of the issues, grouped by …
```
=> Improve error handling on Analysis page

internal/web/web.go, main.go
We use github.com/go-chi/chi to make routing easier with parameters
in URLs, chaining multiple middleware and enforcing HTTP methods to
certain routes.
chi recently changed their import path during the v2 to v3 upgrade
from github.com/pressly/chi to github.com/go-chi/chi, removed
(although the change log states deprecated) the file server helper
and changed the URL parameters placeholders from `/:id` to `/{id}`.
This change updates the import path, implements our own file server
helper (based on their example), and updates the URL parameters
placeholder.
=> Upgrade chi router from v2 to v3

.env.example, internal/analyser/docker.go, internal/analyser/docker_test.go, internal/analyser/filesystem.go, internal/analyser/filesystem_test.go, main.go
Previously any tool running could consume all available RAM
and swap causing availability issues if the offending process
isn't terminated quickly.
This change adds a configuration parameter to limit the amount
of RAM a process can use. If it exceeds this limit, the process
is terminated, but other processes can continue.
Although we have a Filesystem analyser, which can only limit
memory usage via ulimit, the Docker analyser also uses this
mechanism because Docker's own memory limit will terminate the
container, not just the offending process. I.e. the limit cannot
be applied to our exec instance, only when we've created the
container.
We're also required to run the ulimit command each time, because
each tool is executed with a new shell, which won't inherit the
limits put in place by …
=> Limit virtual memory for linters

internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/analyser/cloner_test.go, internal/analyser/configReader_test.go, internal/analyser/refReader_test.go, internal/db/db.go, internal/db/mockdb.go, internal/db/sqldb.go, internal/db/sqldb_test.go, internal/github/handlers.go, internal/web/static/site.css, internal/web/templates/analysis.tmpl, internal/web/web.go, main.go, migrations/7_outputs.sql
Analysis to accept an Executer instead of creating its own
```
Previously I was trying to keep as much logic out of the GitHub
specific handler as I could that wasn't directly GitHub related.
So the analyser creating its own execution environment was OK
initially. But it's added some knowledge the Analyser doesn't
require, and eventually the analyser will be refactored more into
its own parts the the Analyse method may just run a single tool
and a constructor will prepare the environment for the tools.
Also, we'll soon be wanting to wrap/decorate the Executer to have
the database log the output of all the commands being issued.
So the GitHub handler, that already knew about the analyser keeps
that knowledge to itself and just passes a working executor and
manages the clean up itself.
``` …
=> Analysis page to show output 

internal/analyser/analyser.go, internal/analyser/analyser_test.go
Summary page now shows the output of all process run, it'll be
helpful for users to see:
- Go version: we change this on behalf of the user as newer versions
are released, and may allow users to chose a version later.
- Go environment: we may need to adjust some environment parameters
to support different versions and other options that the user may
need to be aware of.
- Limits: we limit the maximum virtual memory a process can use and
other limits are in place, users should be able to see these limits.
- OS Release: users have the ability to install apt packages, as a
result they will need to at least know the distribution version to
know the package names.
We output the versions after (attempting) to read the config file so
future versions that change the environment (such as different …
=> Show environment information in analysis output

integration_test.go, internal/analyser/reporter.go, internal/analyser/reporter_test.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/github/installation_test.go, internal/github/reporters.go, internal/github/reporters_test.go
Previously the GitHub handler was solely responsible for reporting issues, but in the near future, the Analyser package will begin to be responsible for it.
To do this, we'll create an `analyser.Reporter` interface with a single method `Report(context.Context, []db.Issue) error`. GitHub handler is then responsible for determining which reporters it requires and then executing those reporters.
GitHub handler will still be responsible for calling the Report methods, but this will eventually change, and instead, GitHub handler will just be responsible for instantiating the types and passing them to Analyser.
This change is mostly moving the two reporters (Pull Request Comments and Status API) to their own types that implement the `analyser.Reporter` interface.
Additional reporters will be …
=> Refactor into Reporter Interface

Gopkg.lock, internal/github/reporters.go, internal/github/reporters_test.go
GitHub add PRReviewReporter to post create Pull Request Reviews
```
PRReviewReporter uses GitHub's Pull Request Reviews to post issues,
there are multiple benefits, the main being multiple issues result
in just one email to the user.
Additionally, when no issues are detected, a review is still created
with the event APPROVE. This will become configurable at a later
stage as it results in an extra email.
Whilst possible to set the review event to REQUEST_CHANGES, this
hasn't been enabled yet, but will become a configuration option at
a later stage. Instead, the event is set to COMMENT if there are issues
found.
```
Relates to #112.
Going to wait on merging this until I can get a comment on https://platform.github.community/t/api-endpoint-for-pr-reviews/409/21, hopefully, won't be long. …
=> Pull Request Reviews

.env.example, Gopkg.lock, Makefile, health-check.go, internal/analyser/analyser.go, internal/analyser/analyser_test.go, internal/analyser/docker.go, internal/analyser/docker_test.go, internal/db/sqldb.go, internal/github/github.go, internal/github/handlers.go, internal/github/handlers_test.go, internal/github/installation.go, internal/github/reporters.go, internal/github/reporters_test.go, internal/logger/logger.go, internal/logger/logger_test.go, internal/queue/gcp-pubsub.go, internal/queue/gcp-pubsub_test.go, internal/queue/memory.go, internal/queue/memory_test.go, internal/web/web.go, main.go
./internal/logger provides a single logger than all packages can use
to provide:
Levelled logs: Debug is for developers, Info for general production
messages to assist in troubleshooting, Error to be used when an error
occurs that's handled but needs to be raised to an operator and Fatal
which logs the message and terminates execution.
Structured: Using With() to add fields to a message allows operators to
easily view related messages, as GopherCI provides many concurrent
services, it's useful to only inspect message related to a certain
event.
Context: Using With() to return another Logger which logs all messages
with the provided name/key and value. Allows developers to pass along
loggers with information about the event so new clients can be unaware
of the event but still have …
=> Provide application wide logger for structured, levelled with context

integration_test.go, internal/github/handlers.go, internal/github/handlers_test.go, testdata/issue-no-comments.sh
```
For pull requests, this enables the Pull Request Review reporter to
approve pull requests or post comments if issues are found.
The unit test for GitHub has been simplified further to just check
if a comment has been made. In the future the github package won't
require this mocking at all as it will just provide reports to an
analyse function, and instead rely on the integration tests to ensure
issues are reported.
An additional integration test has been included to verify a review
is posted when there are no issues, and its state is APPROVED.
```
Resolves #112.
=> GitHub to post reviews using PRReviewReporter by default
